# Pandas

Для работы с табличными данными служит библиотека pandas. Основной объект в pandas - датафрейм, это таблица с методами упрощающими разные манипуляции с данными. Чтобы создать датафрейм, можно руками вписать данные в виде словаря, а можно загрузить csv файл.

Первым делом нужно подключить сам pandas и загрузить наш файл, возьмём `orders.csv`, передаём его название как аргумент в функцию pandas `read_csv`.

In [1]:
import pandas as pd

df = pd.read_csv('analysis_data/df_orders.csv')
df

          order_id  user_id  event_date  order_sum  commission  delivery_fee
0        O2_0_3734        2  2025-01-30    10285.0      1021.0           0.0
1        O2_1_4073        2  2025-01-31    10646.0       768.0         990.0
2        O3_0_3062        3  2025-01-31     9913.0       937.0           0.0
3        O4_0_9154        4  2025-02-04    10654.0      1048.0           0.0
4        O4_1_4157        4  2025-02-11     7066.0       833.0           0.0
...            ...      ...         ...        ...         ...           ...
38005  O22_10_3971       22  2025-02-14     5500.0       686.4           0.0
38006  O22_11_9893       22  2025-02-18    18000.0      1975.0         990.0
38007  O22_12_2047       22  2025-02-22    11500.0       996.7         990.0
38008  O22_13_4676       22  2025-02-25    22000.0      2780.8        1490.0
38009  O22_14_2215       22  2025-02-28     7200.0       933.7           0.0

[38010 rows x 6 columns]

Посмотрим, что мы имеем: у нас есть дата, клиент, сумма, комисcия и статус. Отлично. Часто первый шаг при работе с табличными данными — это понять их структуру и типы данных.

Чтобы вывести датафрейм, достаточно просто написать его название в конце ячейки.

Методы `head` и `tail` выводят первые и последние N строк (по умолчанию 5), я ими не пользуюсь никогда, потому что, во-первых, в блокноте итак удобно выводится начало датафрейма, во-вторых, data wrangler выводит статистики по этим 5 строкам, и можно спутать с нормальной статистикой колонки.

In [2]:
df.head()

    order_id  user_id  event_date  order_sum  commission  delivery_fee
0  O2_0_3734        2  2025-01-30    10285.0      1021.0           0.0
1  O2_1_4073        2  2025-01-31    10646.0       768.0         990.0
2  O3_0_3062        3  2025-01-31     9913.0       937.0           0.0
3  O4_0_9154        4  2025-02-04    10654.0      1048.0           0.0
4  O4_1_4157        4  2025-02-11     7066.0       833.0           0.0

In [3]:
df.tail()

          order_id  user_id  event_date  order_sum  commission  delivery_fee
38005  O22_10_3971       22  2025-02-14     5500.0       686.4           0.0
38006  O22_11_9893       22  2025-02-18    18000.0      1975.0         990.0
38007  O22_12_2047       22  2025-02-22    11500.0       996.7         990.0
38008  O22_13_4676       22  2025-02-25    22000.0      2780.8        1490.0
38009  O22_14_2215       22  2025-02-28     7200.0       933.7           0.0

### Dataframe
Общую информацию о датафрейме можно получить заглянув в следующие поля:
- `shape` - содержит кортеж с формой, количество строк и колонок
- `columns` - содержит список колонок
- `dtypes` - типы данных в каждой колонке

In [4]:
df.shape

(38010, 6)

In [5]:
df.columns

Index(['order_id', 'user_id', 'event_date', 'order_sum', 'commission',
       'delivery_fee'],
      dtype='str')

In [6]:
df.dtypes

order_id            str
user_id           int64
event_date          str
order_sum       float64
commission      float64
delivery_fee    float64
dtype: object

Метод `info()` создан для того, чтобы посмотреть общую информацию о датафрейме: количество строк, количество непустых значений в каждой колонке. Это обычно просто выводят чтобы посмотреть, а не передают дальше в какие-то функции.

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38010 entries, 0 to 38009
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      36941 non-null  str
 1   user_id       38010 non-null  int64
 2   event_date    38010 non-null  str
 3   order_sum     37658 non-null  float64
 4   commission    37658 non-null  float64
 5   delivery_fee  37658 non-null  float64
dtypes: float64(3), int64(1), str(2)
memory usage: 1.7 MB

Метод `describe()` выводит для числовых колонок среднее, минимум, максимум и квартили (это значения на четвертях распределения, то есть квартиль 50% это медиана, и есть квартили 25% и 75%).

In [8]:
df.describe()

            user_id     order_sum    commission  delivery_fee
count  38010.000000  37658.000000  37658.000000  37658.000000
mean   49995.862931  10005.675979    999.150170    108.605874
std    28803.590031   1996.380926    286.007999    351.993334
min        2.000000   2378.000000    144.000000      0.000000
25%    25064.250000   8662.000000    797.000000      0.000000
50%    50072.500000  10008.000000    980.000000      0.000000
75%    74747.250000  11343.000000   1179.000000      0.000000
max    99997.000000  22000.000000   2780.800000   1490.000000

### Series
Каждая колонка в датафрейме - это объект класса `Series`. Получить его можно обратившись к датафрейму как будто по ключу словаря.

У колонки можно вызывать различные статистические методы, например `value_counts()` — частоты значений, `mean()` — среднее, `nunique()` — сколько уникальных.

In [9]:
df['delivery_fee'].value_counts()

delivery_fee
0.0       34246
990.0      1988
1490.0     1424
Name: count, dtype: int64

In [10]:
df['order_sum'].mean()

np.float64(10005.675978543735)

In [11]:
df['user_id'].nunique()

33831

Ещё часто смотрят пропуски: метод `isna()` вернёт маску (колонку с True/False). Сам по себе этот метод бесполезен, нужно посчитать количество или долю значений True с помощью `sum()`.

In [12]:
df['order_id'].isna().sum()

np.int64(1069)

### Method chaining
В pandas принят стиль кода, когда прямо для того что возвращает один метод, вызывается следующий метод, и можно записать подряд много преобразований (method chaining).

In [13]:
# Цепочка методов:
# 1. Берем колонку order_id
# 2. Проверяем на пропуски (isna возвращает True/False)
# 3. Считаем долю пропусков (mean считает долю True)
missing_ratio = (
    df["order_id"]
    .isna()
    .mean()
)
missing_ratio

np.float64(0.028124177847934754)

### Фильтрации
Чтобы выбирать из большого датафрейма строки по определённому условию, используются фильтрации. Мы пишем `df` и в квадратных скобках даём булеву маску.

Выберем заказы, где сумма заказа больше 10 000.

Двойные квадратные скобки позволяют выбрать несколько колонок по списку.

In [14]:
big_orders = df[df["order_sum"] > 10000]
big_orders[["event_date", "order_sum", "commission", "delivery_fee"]]

       event_date  order_sum  commission  delivery_fee
0      2025-01-30    10285.0      1021.0           0.0
1      2025-01-31    10646.0       768.0         990.0
3      2025-02-04    10654.0      1048.0           0.0
6      2025-01-05    10856.0       549.0           0.0
7      2025-01-02    11142.0      1367.0           0.0
...           ...        ...         ...           ...
38000  2025-01-18    22000.0      1957.3           0.0
38001  2025-01-22    18000.0      2224.3         990.0
38006  2025-02-18    18000.0      1975.0         990.0
38007  2025-02-22    11500.0       996.7         990.0
38008  2025-02-25    22000.0      2780.8        1490.0

[18896 rows x 4 columns]

Булева маска - это колонка того же размера, но заполненная булевым значением, которое получается по определённому условию. Всё что как-то связано с проверкой по условию в pandas, возвращает её.

In [15]:
df["order_sum"] > 10000

0         True
1         True
2        False
3         True
4        False
         ...
38005    False
38006     True
38007     True
38008     True
38009    False
Name: order_sum, Length: 38010, dtype: bool

In [16]:
df['order_id'].isna()

0        False
1        False
2        False
3        False
4        False
         ...
38005    False
38006    False
38007    False
38008    False
38009    False
Name: order_id, Length: 38010, dtype: bool

Часто фильтруют по нескольким условиям сразу. В pandas для этого используют логические операторы: `&` (и), `|` (или). Каждое условие обязательно берём в круглые скобки.

In [17]:
# Отбираем заказы с платной доставкой и суммой больше 10000
df_filtered = df[(df["delivery_fee"] > 0) & (df["order_sum"] > 10000)]
df_filtered[["event_date", "order_sum", "commission", "delivery_fee"]]

       event_date  order_sum  commission  delivery_fee
1      2025-01-31    10646.0       768.0         990.0
30     2025-02-18    11637.0      1195.0        1490.0
41     2025-02-10    10241.0       813.0         990.0
77     2025-02-05    13478.0      1612.0         990.0
133    2025-01-23    12740.0       858.0        1490.0
...           ...        ...         ...           ...
37987  2025-01-15    15634.0      1300.0        1490.0
38001  2025-01-22    18000.0      2224.3         990.0
38006  2025-02-18    18000.0      1975.0         990.0
38007  2025-02-22    11500.0       996.7         990.0
38008  2025-02-25    22000.0      2780.8        1490.0

[1685 rows x 4 columns]

Фильтрация по списку значений делается методом `isin()`. А даты в формате строк можно сравнивать как обычные значения.

In [18]:
paid_delivery = df[df["delivery_fee"].isin([990, 1490])]
paid_delivery["delivery_fee"].value_counts()

delivery_fee
990.0     1988
1490.0    1424
Name: count, dtype: int64

In [19]:
df[df['event_date'] >= "2025-03-01"]

            order_id  user_id  event_date  order_sum  commission  delivery_fee
1934    O5047_1_5705     5047  2025-03-01    12220.0      1375.0           0.0
2587    O6769_2_2138     6769  2025-03-01     7620.0       709.0           0.0
2847    O7494_1_3602     7494  2025-03-01    10519.0       950.0           0.0
4530   O12112_1_1785    12112  2025-03-01     6185.0       818.0           0.0
6302   O16720_1_5819    16720  2025-03-01    11273.0       842.0           0.0
...              ...      ...         ...        ...         ...           ...
35638  O93708_1_3539    93708  2025-03-01    10410.0      1123.0         990.0
36739  O96672_1_1581    96672  2025-03-01     6374.0       670.0           0.0
36999  O97383_1_9519    97383  2025-03-01     7847.0       883.0           0.0
37330  O98290_1_1221    98290  2025-03-01     9023.0       576.0           0.0
37818  O99567_1_6633    99567  2025-03-01    10196.0       926.0           0.0

[78 rows x 6 columns]

### Редактирование колонок
Найдём дубликаты. Метод `duplicated()` возвращает булеву маску дублей. `keep=False` помечает все повторения, включая первое, чтобы мы увидели всю группу дублей.

In [20]:
df[df["order_id"].duplicated(keep=False)].sort_values("order_id")

      order_id  user_id  event_date  order_sum  commission  delivery_fee
14         NaN       28  2025-02-17     8635.0       855.0           0.0
49         NaN      117  2025-02-08    11726.0       986.0           0.0
116        NaN      294  2025-01-05        NaN         NaN           NaN
188        NaN      470  2025-02-13        NaN         NaN           NaN
250        NaN      622  2025-02-24    10045.0       547.0         990.0
...        ...      ...         ...        ...         ...           ...
37940      NaN    99869  2025-01-10        NaN         NaN           NaN
37955      NaN    99895  2025-02-10    10167.0       589.0           0.0
37957      NaN    99901  2025-01-28        NaN         NaN           NaN
37958      NaN    99902  2025-01-11        NaN         NaN           NaN
37967      NaN    99921  2025-01-15    11202.0       901.0           0.0

[1069 rows x 6 columns]

Удалим дубликаты методом `drop_duplicates()`.

In [21]:
# Удаляем повторяющиеся строки по order_id, оставляем только первую
df = df.drop_duplicates(subset=["order_id"], keep="first")
df

          order_id  user_id  event_date  order_sum  commission  delivery_fee
0        O2_0_3734        2  2025-01-30    10285.0      1021.0           0.0
1        O2_1_4073        2  2025-01-31    10646.0       768.0         990.0
2        O3_0_3062        3  2025-01-31     9913.0       937.0           0.0
3        O4_0_9154        4  2025-02-04    10654.0      1048.0           0.0
4        O4_1_4157        4  2025-02-11     7066.0       833.0           0.0
...            ...      ...         ...        ...         ...           ...
38005  O22_10_3971       22  2025-02-14     5500.0       686.4           0.0
38006  O22_11_9893       22  2025-02-18    18000.0      1975.0         990.0
38007  O22_12_2047       22  2025-02-22    11500.0       996.7         990.0
38008  O22_13_4676       22  2025-02-25    22000.0      2780.8        1490.0
38009  O22_14_2215       22  2025-02-28     7200.0       933.7           0.0

[36942 rows x 6 columns]

Для просмотра пропусков в нескольких колонках сразу можно использовать `isna().sum()`.

In [22]:
df[["event_date", "order_sum", "commission", "delivery_fee"]].isna().sum()

event_date      0
order_sum       0
commission      0
delivery_fee    0
dtype: int64

### Преобразования таблиц
Метод `concat` нужен для объединения таблиц. `axis=0` склеивает по строкам (друг под другом), `axis=1` по столбцам.

In [23]:
events = pd.read_csv("analysis_data/df_events.csv")

# Разделим события на две части для примера
events_early = events[events["event_date"] < "2025-02-15"]
events_late = events[events["event_date"] >= "2025-02-15"]

# Склеиваем два датафрейма по строкам
events_all = pd.concat([events_early, events_late], axis=0)
events_all

        user_id  event_date       event_type order_id feedback_id
0             1  2025-02-08  main_page.shown      NaN         NaN
1             1  2025-02-08       item.added      NaN         NaN
2             1  2025-02-08       cart.shown      NaN         NaN
3             1  2025-02-08   checkout.shown      NaN         NaN
4             2  2025-01-30  main_page.shown      NaN         NaN
...         ...         ...              ...      ...         ...
378273    99994  2025-02-26  main_page.shown      NaN         NaN
378274    99994  2025-02-26       item.added      NaN         NaN
378296   100000  2025-02-17  main_page.shown      NaN         NaN
378297   100000  2025-02-17       item.added      NaN         NaN
378298   100000  2025-02-17       cart.shown      NaN         NaN

[378299 rows x 5 columns]

Загрузим табличку где каждому юзеру присвоена группа А или В

In [24]:
matching = pd.read_csv("analysis_data/df_matching.csv")
matching

       user_id exp_group  event_date
0        51426         A  2025-01-01
1        58884         A  2025-01-01
2        77834         A  2025-01-01
3        42968         A  2025-01-01
4        55854         A  2025-01-01
...        ...       ...         ...
99995    48364         A  2025-02-28
99996    78084         A  2025-02-28
99997    98431         B  2025-02-28
99998    98457         B  2025-02-28
99999    45359         B  2025-02-28

[100000 rows x 3 columns]

Метод `merge` — аналог JOIN в SQL. Параметр `on` задаёт общий ключ, а `how` тип соединения (`left`, `inner`, `right`, `outer`).

In [25]:
orders_with_group = df.merge(
    matching[["user_id", "exp_group"]],
    on="user_id", # ключ, по которому ищем совпадения
    how="left" # оставляем все строки левой таблицы (df)
)
orders_with_group[["order_id", "user_id", "exp_group", "order_sum"]]

          order_id  user_id exp_group  order_sum
0        O2_0_3734        2         A    10285.0
1        O2_1_4073        2         A    10646.0
2        O3_0_3062        3         B     9913.0
3        O4_0_9154        4         A    10654.0
4        O4_1_4157        4         A     7066.0
...            ...      ...       ...        ...
36937  O22_10_3971       22         A     5500.0
36938  O22_11_9893       22         A    18000.0
36939  O22_12_2047       22         A    11500.0
36940  O22_13_4676       22         A    22000.0
36941  O22_14_2215       22         A     7200.0

[36942 rows x 4 columns]

Метод `pivot_table` позволяет "повернуть" таблицу (из long формата в wide), применяя агрегационные функции.

In [26]:
events_pivot = events.pivot_table(
    index="user_id",
    columns="event_type",
    values="event_date", # колонка, по которой считаем
    aggfunc="count", # считаем количество событий
    fill_value=0 # заполняет нулями те типы событий, которых у пользователя не было
)
events_pivot

event_type,cart.shown,checkout.shown,item.added,main_page.shown,order.created,support.feedback_submitted
user_id,,,,,,
1,1,1,1,1,0,0
2,2,2,2,2,2,0
3,1,1,1,1,1,0
4,2,2,2,2,2,0
5,0,0,0,1,0,0
...,...,...,...,...,...,...
99996,1,0,1,1,0,0
99997,1,1,2,2,1,0
99998,1,1,1,1,0,0
99999,1,1,1,1,0,0
100000,1,0,1,1,0,0

### Группировки и агрегации
Сначала `groupby()` — выбираем, по чему группируем, потом `agg()` — выбираем, что именно считаем.

In [27]:
# Группируем по экспериментальной группе и считаем несколько метрик сразу
orders_group_metrics = (
    orders_with_group
    .groupby("exp_group")
    .agg(
        orders_cnt=("order_id", "nunique"),    # Уникальные заказы
        users_cnt=("user_id", "nunique"),      # Уникальные пользователи
        avg_order_sum=("order_sum", "mean"),   # Средний чек
        total_revenue=("order_sum", "sum"),    # Общая выручка
        avg_commission=("commission", "mean"),
    )
)
orders_group_metrics

           orders_cnt  users_cnt  avg_order_sum  total_revenue  avg_commission
exp_group
A               19322      16893   10010.312219    193429263.0      998.424629
B               17619      16108    9999.140303    176174853.0      999.792553

Для группировки по датам, чтобы увидеть динамику, используем `pd.Grouper` с указанием частоты (`freq="D"` для дней). Предварительно приведём колонку дат к типу `datetime`.

In [28]:
# pd.to_datetime конвертирует строки в объекты дат
# assign создает или перезаписывает колонку
orders_daily = (
    df.assign(event_date=pd.to_datetime(df["event_date"]))
    .groupby(pd.Grouper(key="event_date", freq="D"))
    .agg(
        orders_cnt=("order_id", "nunique"),
        revenue=("order_sum", "sum"),
        avg_check=("order_sum", "mean"),
    )
)
orders_daily

            orders_cnt    revenue     avg_check
event_date
2025-01-01         569  5726498.0  10064.144112
2025-01-02         544  5397398.0   9921.687500
2025-01-03         570  5616895.0   9854.201754
2025-01-04         597  6031643.0  10103.254606
2025-01-05         579  5726542.0   9890.400691
2025-01-06         564  5698718.0  10104.109929
2025-01-07         641  6367405.0   9933.549142
2025-01-08         615  6107465.0   9930.837398
2025-01-09         641  6414142.0  10006.461778
2025-01-10         639  6433789.0  10068.527387
2025-01-11         665  6726629.0  10115.231579
2025-01-12         596  6013719.0  10090.132550
2025-01-13         613  6164710.0  10056.623165
2025-01-14         663  6642985.0  10019.585219
2025-01-15         638  6356425.0   9963.048589
2025-01-16         646  6538930.0  10122.182663
2025-01-17         666  6605013.0   9917.436937
2025-01-18         635  6375041.0  10039.434646
2025-01-19         626  6274096.0  10022.517572
2025-01-20         666  6707463.0  10071.265766
2025-01-21         590  5935215.0  10059.686441
2025-01-22         662  6587454.0   9950.836858
2025-01-23         626  6245836.0   9977.373802
2025-01-24         604  6068961.0  10047.948675
2025-01-25         618  6242595.0  10101.286408
2025-01-26         662  6626174.0  10009.326284
2025-01-27         639  6353419.0   9942.752739
2025-01-28         613  6072407.0   9906.047308
2025-01-29         636  6341983.0   9971.671384
2025-01-30         643  6417796.0   9981.020218
2025-01-31         633  6350732.0  10032.751975
2025-02-01         632  6424263.0  10164.973101
2025-02-02         650  6476177.0   9963.349231
2025-02-03         636  6401338.0  10064.996855
2025-02-04         651  6465650.0   9931.874040
2025-02-05         631  6319479.0  10015.022187
2025-02-06         614  6106064.0   9944.729642
2025-02-07         631  6296136.0   9978.028526
2025-02-08         626  6270051.0  10016.055911
2025-02-09         602  5911354.0   9819.524917
2025-02-10         661  6613579.0  10005.414523
2025-02-11         624  6212756.0   9956.339744
2025-02-12         651  6491007.0   9970.824885
2025-02-13         629  6367307.0  10122.904610
2025-02-14         609  6052458.0   9938.354680
2025-02-15         600  6070894.0  10118.156667
2025-02-16         663  6602070.0   9957.873303
2025-02-17         633  6397426.0  10090.577287
2025-02-18         594  5928936.0   9981.373737
2025-02-19         627  6241266.0   9954.172249
2025-02-20         623  6253333.0  10037.452648
2025-02-21         590  5854592.0   9923.037288
2025-02-22         642  6459889.0  10062.132399
2025-02-23         653  6610731.0  10123.630934
2025-02-24         622  6124138.0   9845.881029
2025-02-25         622  6218438.0   9997.488746
2025-02-26         647  6466690.0   9994.884080
2025-02-27         604  6093846.0  10089.149007
2025-02-28         598  5937225.0   9928.469900
2025-03-01          77   768945.0   9986.298701

### Задание

#### Задание 1: Свойства и статистики
1. Загрузите таблицу с событиями `df_events.csv` в переменную `df_events_task`.
2. Сохраните количество строк в `rows_count`.
3. Посчитайте количество уникальных событий `event_type` и сохраните в `unique_events`.

In [ ]:
df_events_task = ...
rows_count = ...
unique_events = ...

assert rows_count == 378299
assert unique_events == 6

In [38]:
events[(events['event_type'] == 'item.added')&(events['event_date'] > '2025-02-10')]

        user_id  event_date  event_type order_id feedback_id
25            4  2025-02-11  item.added      NaN         NaN
37            8  2025-02-23  item.added      NaN         NaN
107          26  2025-02-27  item.added      NaN         NaN
114          28  2025-02-17  item.added      NaN         NaN
121          31  2025-02-14  item.added      NaN         NaN
...         ...         ...         ...      ...         ...
378271    99993  2025-02-24  item.added      NaN         NaN
378274    99994  2025-02-26  item.added      NaN         NaN
378279    99996  2025-02-12  item.added      NaN         NaN
378289    99998  2025-02-13  item.added      NaN         NaN
378297   100000  2025-02-17  item.added      NaN         NaN

[27205 rows x 5 columns]

#### Задание 2: Фильтрация
Оставьте в `df_events_task` только события типа `item.added` за дату после `2025-02-10` и сохраните в `screen_views_late`.

In [ ]:
screen_views_late = ...

assert len(screen_views_late) == 27205
assert screen_views_late.loc[25, 'event_type'] == 'item.added'

#### Задание 3: Слияния (Merge)
Присоедините таблицу `matching` (файл `df_matching.csv`) по `user_id`, чтобы каждому юзеру в `screen_views_late` была присвоена группа. Какой join нужен?

In [ ]:
screen_views_with_group = ...

assert 'exp_group' in screen_views_with_group.columns
assert len(screen_views_with_group) == len(screen_views_late)

#### Задание 4: Группировка и Агрегация
Сгруппируйте `screen_views_with_group` по `exp_group` и посчитайте количество уникальных пользователей (`user_id`) в каждой группе.